server:
  port: 8085

# Configuration for MySQL Database
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/userschema
    username: root
    password: Priya@1998
    driver-class-name: com.mysql.cj.jdbc.Driver