server:
  port: 8889

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          #uri: ${HOME}/IdeaProjects/configrepo
          #uri: /c/Users/Windows/IdeaProjects/configrepo
          uri: file:///C:/Users/Windows/IdeaProjects/configrepo/
          #uri: https://github.com/priyadharshinisenthilvel24/springcloudconfig

          #cloneOnStart: true
          repos:
            test-repo:
              pattern: userandrolemodule/test
              uri: https://github.com/priyadharshinisenthilvel24/springcloudconfig/configslocation
              search-paths:
                - userandrolemodule/{profile}

            prod-repo:
              pattern: userandrolemodule/prod
              uri: https://github.com/priyadharshinisenthilvel24/springcloudconfig/configslocation
              search-paths:
                - userandrolemodule/{profile}

            any-repo:
              uri: https://github.com/priyadharshinisenthilvel24/springcloudconfig/configslocation
              pattern: userandrolemodule*/*
              search-paths:
                - userandrolemodule/{application}/{profile}
my:
  greeting: Hello World from cloud config